global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - pve-artemis.ntcl.pl:9100
        - pve-hestia.ntcl.pl:9100
        # - prod-01.ntcl.pl:9100
        - mon-01.ntcl.pl:9100

  - job_name: 'pve'
    static_configs:
      - targets:
        - pve-artemis.ntcl.pl
          #- pve-hestia.ntcl.pl
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221  # PVE exporter.

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        # - prod-01.ntcl.pl:8081
        - cadvisor:8080
  
  - job_name: 'graphite-exporter'
    static_configs:
      - targets:
          - graphite-exporter:9108

  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']
