---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - icon: si-github-#FFFFFF
          href: https://github.com/
    - Cloudflare:
      - icon: cloudflare
        href: https://dash.cloudflare.com
    - OVH:
      - icon: si-ovh-#FFFFFF
        href: https://www.ovh.com/manager

- Social:
    - Reddit:
        - icon: reddit
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/
