---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: ntcl.pl homepage
headerStyle: boxed


showStats: true
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
