services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    user: 0:0
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=1y
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ../../volumes/prometheus/prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOSTNAME}`)
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=cfresolver
      - traefik.docker.network=frontend
networks:
  frontend:
    external: true
