services:
  promtail:
    command: -config.file=/etc/promtail/promtail-config.yaml
    container_name: promtail
    image: grafana/promtail:latest
    networks:
      - frontend
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: unless-stopped
    volumes:
    - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
    - ../../volumes/promtail_syslog/logs:/var/log:ro

  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      - frontend
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: unless-stopped
    volumes:
    - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
    - ../../volumes/promtail_syslog/logs:/var/log/syslog-ng

networks:
  frontend:
    external: true