services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - APP_URL=https://bookstack.ntcl.pl
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=1234
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstack.rule=Host(`bookstack.ntcl.pl`)
      - traefik.http.routers.bookstack.entrypoints=websecure
      - traefik.http.routers.bookstack.tls=true
      - traefik.http.routers.bookstack.tls.certresolver=cfresolver
      - traefik.docker.network=frontend
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=1234
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
