services:
  traefik:
    image: docker.io/library/traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/docker/volumes/traefik/config/conf/:/etc/traefik/conf/
      - ~/docker/volumes/traefik/config/certs/:/etc/traefik/certs/
    networks:
      - frontend
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      # - --api.dashboard=true
      # - --api.insecure=true
      - --certificatesresolvers.cfresolver.acme.dnschallenge=true
      - --certificatesresolvers.cfresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cfresolver.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.cfresolver.acme.storage=/etc/traefik/certs/acme.json
      - --certificatesResolvers.cfresolver.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
networks:
  frontend:
    external: true
